spring:
  datasource:
    url: jdbc:mysql://monorail.proxy.rlwy.net:57860/railway
    username: root
    password: PsGEJivjqPXqFuHHzfNXbunvcRoIfKOD
    driverClassName: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop

management:
  endpoints:
    web:
      exposure:
        include: "*"