server:
  port: 8888

spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/ludinhdung/configuration-server.git

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


